version: '3.8'
services:
  database:
    image: postgres:latest
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - intranet
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U rentlink"
      interval: 10s
      timeout: 3s
      retries: 10

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@rentlink.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "9090:80"
    depends_on:
      database:
        condition: service_healthy

  rentlink:
    build: .
    links:
      - database:database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - intranet
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/rentlink"

networks:
  intranet: