version: '3.8'
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/init-kratos-user.sql:/tmp/kratos.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - intranet
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U rentlink"
      interval: 10s
      timeout: 3s
      retries: 10

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@rentlink.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "9090:80"
    depends_on:
      database:
        condition: service_healthy

  rentlink:
    container_name: rentlink
    build: .
    links:
      - database:database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - intranet
    ports:
      - "8081:8081"
    volumes:
      - ./local_files:/opt/rentlink/files
    environment:
      PORT: 8081
      DATABASE_URL: "jdbc:postgresql://database:5432/rentlink"
      MAIL_USERNAME: "support@rentlink.io"
      MAIL_PASSWORD: /run/secrets/rentlink_smtp_password
    secrets:
      - rentlink_smtp_password

  kratos-migrate:
    image: oryd/kratos:v1.0.0
    links:
      - database:database
    environment:
      - DSN=postgres://root:root@database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: kratos
    image: oryd/kratos:v1.0.0
    links:
      - database:database
    environment:
      - DSN=postgres://root:root@database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
      - "1025:1025"
    networks:
      - intranet

  oathkeeper:
    container_name: oathkeeper
    image: oryd/oathkeeper:v0.40.6
    depends_on:
      - kratos
    ports:
      - 8080:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

networks:
  intranet:

secrets:
  rentlink_smtp_password:
    file: ./smtp_password