version: '3.8'
services:
  database:
    image: postgres:15.0
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
  rentlink:
    build: .
    links:
      - database:database
    depends_on:
      - database
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/rentlink
