server:
  port: ${PORT:8082}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rentlink}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    password: root
    user: root
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rentlink}
    schemas: rentlink
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
#  mail:
#    host: localhost
#    port: 1025
#    username: test
#    password: test
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: false

rentlink:
  images:
    dir: "/opt/rentlink/images/"
  files:
    dir: "/opt/rentlink/files/"

