server:
  port: ${PORT:8082}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rentlink}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    password: root
    user: root
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rentlink}
    schemas: rentlink
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  mail:
    host: ssl0.ovh.net
    port: 587
    username: ${MAIL_USERNAME:support@rentlink.io}
    password: ${MAIL_PASSWORD:changeit}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: true

rentlink:
  images:
    dir: "/opt/rentlink/images/"
  files:
    dir: "/opt/rentlink/files/"
